### ISSUE TITLE
Question about AdaptiveMaxPooling

### ISSUE THREAD

**Issue by sonnguyen129** [babaid/Alzheimer-Classification#1]
Hi @babaid 
I don't understand the relationship between the output size of the AdaptiveMaxPool layer and the previous layers. Hope you will explain it to me.
Thank you so much

**Comment by babaid** [comment]
Adaptive Maxpool layers let you specify the output size, so there does not have to be any correlation with the previous outputs. (As I see I left some junk comments in the code, I will clean it)

**Comment by sonnguyen129** [comment]
Hi @babaid 
Thank you for your reply. So how is adaptive pooling different from basic pooling? I mean advantages. Why should we use it instead of basic pooling?
Thank you

**Comment by babaid** [comment]
In my experience it's only advantage is that you dont have to calculute the typical parameters a pooling layer would require by yourself, and you still know exactly the output. Other than that, it's nothing more than a simple pooling layer.

**Comment by sonnguyen129** [comment]
Thank you for your reply.
